[package]
name = "trust-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "trust-engine"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hamilton-contracts = { workspace = true }
trust-detectors = { workspace = true }
trust-aggregator = { workspace = true }
trust-library = { workspace = true }
trust-transport = { workspace = true }
trust-server = { workspace = true }
rumqttc = { workspace = true }
