//! Shared test inputs from the WS-A fixture spine
//! (`packages/contracts/fixtures/aoe/`, generated by `gen_fixtures.py --contract-out`).
//! The estimator itself never reads them: they are test-only.
#![allow(dead_code)]

use std::path::PathBuf;

use serde_json::Value;
use trust_estimator::*;

pub fn fixture(name: &str) -> Value {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../../packages/contracts/fixtures/aoe")
        .join(name);
    let s = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
    serde_json::from_str(&s).expect("fixture JSON")
}

pub fn golden() -> Value {
    fixture("golden-cases.json")
}

pub fn f(v: &Value) -> f64 {
    v.as_f64()
        .unwrap_or_else(|| panic!("number expected, got {v}"))
}

pub fn rx_class(s: &str) -> RxClass {
    serde_json::from_value(Value::String(s.to_string())).expect("rx_class")
}

pub struct Scenario {
    pub method: MethodModel,
    pub receivers: Receivers,
    pub grid: Grid,
    pub lat0: f64,
    pub lon0: f64,
    pub km_per_deg_lon: f64,
}

impl Scenario {
    pub fn to_latlon(&self, x: f64, y: f64) -> (f64, f64) {
        (
            self.lat0 + y / grid::KM_PER_DEG_LAT,
            self.lon0 + x / self.km_per_deg_lon,
        )
    }
}

/// Method, receivers (the fixture's classes: civil + mil) and the fixture's grid
/// and prior (FLOT at x = flot_x_km, enemy east, standoff band).
pub fn scenario(g: &Value) -> Scenario {
    let m = &g["model"];
    let o = &m["origin"];
    let (lat0, lon0) = (f(&o["lat"]), f(&o["lon"]));
    assert_eq!(f(&o["km_per_deg_lat"]), grid::KM_PER_DEG_LAT);
    let km_per_deg_lon = grid::KM_PER_DEG_LAT * lat0.to_radians().cos();
    assert!((km_per_deg_lon - f(&o["km_per_deg_lon"])).abs() < 1e-6);
    let pr = &m["prior"];
    let flot_x = f(&pr["flot_x_km"]);
    let ll = |x: f64, y: f64| LatLon {
        lat: lat0 + y / grid::KM_PER_DEG_LAT,
        lon: lon0 + x / km_per_deg_lon,
    };
    let standoff = &pr["standoff"];
    assert_eq!(standoff["enabled"], true);
    let mut classes: Vec<ReceiverClass> = m["thresholds_db"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| ReceiverClass {
            rx_class: rx_class(k),
            js_threshold_db: f(v),
        })
        .collect();
    classes.sort_by_key(|c| c.rx_class);
    let link = &m["link"];
    let gr = &m["grid"];
    Scenario {
        method: MethodModel {
            method_id: "ground_based_gps_uhf_barrage".into(),
            erp_dbm: m["hypotheses"]["erp_dbm"]
                .as_array()
                .unwrap()
                .iter()
                .map(f)
                .collect(),
            mast_m: m["hypotheses"]["mast_m"]
                .as_array()
                .unwrap()
                .iter()
                .map(f)
                .collect(),
            sigma_db: f(&m["sigma_db"]),
            affects_rx_classes: vec![RxClass::GnssCivil, RxClass::GnssMil, RxClass::UhfComms],
        },
        receivers: Receivers {
            signal_dbm: f(&link["s_dbm"]),
            rx_gain_dbi: f(&link["g_r_jam_dbi"]),
            rx_height_m: f(&link["h_rx_m"]),
            freq_mhz: f(&link["f_mhz"]),
            classes,
        },
        grid: Grid {
            origin: LatLon {
                lat: lat0,
                lon: lon0,
            },
            cell_m: f(&gr["res_km"]) * 1000.0,
            x_km: [f(&gr["x_km"][0]), f(&gr["x_km"][1])],
            y_km: [f(&gr["y_km"][0]), f(&gr["y_km"][1])],
            flot: Some(Flot {
                points: vec![ll(flot_x, -12.0), ll(flot_x, 12.0)],
                enemy_side: Side::Right,
            }),
            prior: PriorModel {
                enemy_weight: f(&pr["enemy_side"]),
                friendly_weight: f(&pr["friendly_side"]),
                standoff_km: [
                    f(&standoff["band_km_behind_flot"][0]),
                    f(&standoff["band_km_behind_flot"][1]),
                ],
                outside_standoff_weight: f(&standoff["outside_band_weight"]),
            },
        },
        lat0,
        lon0,
        km_per_deg_lon,
    }
}

/// The estimator input of one run: every evidence row's per-class state and position.
pub fn evidence(run: &Value, now_ms: i64) -> Evidence {
    Evidence {
        now_ms,
        observations: run["evidence"]
            .as_array()
            .unwrap()
            .iter()
            .map(|o| Observation {
                source_id: o["source_id"].as_str().unwrap().into(),
                rx_class: rx_class(o["rx_class"].as_str().unwrap()),
                state: match o["state"].as_str().unwrap() {
                    "degraded" => UnitState::Degraded,
                    "healthy" => UnitState::Healthy,
                    s => panic!("state {s}"),
                },
                lat: f(&o["lat"]),
                lon: f(&o["lon"]),
            })
            .collect(),
    }
}

/// A demo beat run (`demo_b115`, `demo_b150`).
pub fn demo_run<'a>(g: &'a Value, id: &str) -> &'a Value {
    g["demo"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["id"] == id)
        .unwrap_or_else(|| panic!("demo run {id}"))
}

/// A seed sweep (`demo_truth_seed_sweep`, `off_node_seed_sweep`, `back_lobe_seed_sweep`).
pub fn sweep<'a>(g: &'a Value, id: &str) -> &'a Value {
    g["sweeps"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["id"] == id)
        .unwrap_or_else(|| panic!("sweep {id}"))
}

/// Row-major index of a fixture `truth_cell {ix, iy}` on the fixture grid.
pub fn truth_cell(a: &Analysis, cell: &Value) -> usize {
    let (ix, iy) = (
        cell["ix"].as_u64().unwrap() as usize,
        cell["iy"].as_u64().unwrap() as usize,
    );
    assert!(ix < a.geom.nx && iy < a.geom.ny);
    let c = iy * a.geom.nx + ix;
    // The fixture's cell centre is the grid's.
    assert!((a.geom.x(ix) - f(&cell["x_km"])).abs() < 1e-9);
    assert!((a.geom.y(iy) - f(&cell["y_km"])).abs() < 1e-9);
    c
}

/// Is the truth cell inside the HPD 90% region? `None` when the run is unbounded.
pub fn contained(a: &Analysis, cell: &Value) -> Option<bool> {
    let c = truth_cell(a, cell);
    a.posterior.as_ref().map(|p| p.pe[c] >= p.thr90)
}
