[package]
name = "trust-aggregator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
hamilton-contracts = { workspace = true }
trust-detectors = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
